### ISSUE TITLE
Possible error in loss_fn.m

### ISSUE THREAD

**Issue by jesseli2002** [aransena/alphaTPGMR#1]
I believe there's an error in the implementation of `fn/loss_fn.m`. Currently, the the central `sum_error` line looks like this (after breaking down the line for clarity): 
```matlab
sum_error = sum_error ...
           + (s(n).Data(2,i)-test_set(n).Data(2,i)^2 ...
           + (s(n).Data(3,i)-test_set(n).Data(3,i))^2);
```
But the parentheses make the operators erratic. I think more correct would be
```matlab
sum_error = sum_error ...
    + (s(n).Data(2,i) - test_set(n).Data(2,i))^2 ...
    + (s(n).Data(3,i) - test_set(n).Data(3,i))^2;
```
While I'm here - if I'm understanding correctly, this function doesn't seem to implement the weightings in the objective function, as described by the paper?

**Comment by aransena** [comment]
Many thanks for notifying me, it appears I copied over the wrong loss function file to this repo, apologies.

This has now been updated, reflecting the loss function in the paper.
